### PR TITLE
Update changelog up to 4.0.54

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by MGaetan89** [comment]
@duramato Can you update it to 4.0.54 please?

https://github.com/SiCKRAGETV/SickRage/compare/v4.0.53...v4.0.54

**Comment by duramato** [comment]
@MGaetan89 yes

**Comment by duramato** [comment]
@MGaetan89 done ;)

**Comment by MGaetan89** [comment]
Thanks :)
Now we wait for @miigotu or @fernandog for the final click ;)

**Comment by miigotu** [comment]
@duramato
SiCKRAGETV/SickRage/releases/tag/v4.0.55
SiCKRAGETV/SickRage/compare/v4.0.54...v4.0.55

**Comment by duramato** [comment]
@miigotu sure just give me a few minutes

**Comment by MGaetan89** [comment]
I don't if it's because I worked on it or if it is real, but I got the impression that the performance are noticeable.
The shows list is displayed faster, but the progress indicator still loads for a few seconds. So we can do more :D

**Comment by miigotu** [comment]
@MGaetan89 It is faster. I've profiled it and it takes less than half the time it did 2 releases ago to load the main show page.

It's mostly because we have etags working now and all the images are 304 and loaded from browser cache.

If we get static_path/static_url with tornado's cachebreaker working then 1x 301 redirect per show poster/thumb/banner is removed (108B transfer), and 1x request/304 per image on the page is removed (108B tranfser)

The smaller js/css definitely helps too, but I think the js needs hella work still.

**Pull request merged**
